// swift-tools-version:5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

#if os(Windows)
let platformAbseilSources = [
    "third_party/absl/time/internal/cctz/src/time_zone_name_win.cc",
]
#else
let platformAbseilSources: [String] = []
#endif

let package = Package(
    name: "swift-package-support-sentencepiece",
    products: [
        .library(
            name: "swift-package-support-sentencepiece",
            targets: ["swift-package-support-sentencepiece"]
        ),
        .executable(name: "spm_encode", targets: ["spm_encode"]),
        .executable(name: "spm_decode", targets: ["spm_decode"]),
        .executable(name: "spm_normalize", targets: ["spm_normalize"]),
        .executable(name: "spm_train", targets: ["spm_train"]),
        .executable(name: "spm_export_vocab", targets: ["spm_export_vocab"]),
    ],
    targets: [
        .target(
            name: "swift-package-support-sentencepiece",
            path: ".",
            exclude: [
                "python",
                "doc",
                "data",
                "cmake",
                "contrib",
                ".github",
                // Test files
                "src/bpe_model_test.cc",
                "src/bpe_model_trainer_test.cc",
                "src/builder_test.cc",
                "src/char_model_test.cc",
                "src/char_model_trainer_test.cc",
                "src/filesystem_test.cc",
                "src/freelist_test.cc",
                "src/invalid_model_test.cc",
                "src/model_factory_test.cc",
                "src/model_interface_test.cc",
                "src/normalizer_test.cc",
                "src/sentencepiece_processor_benchmarks_test.cc",
                "src/sentencepiece_processor_parallel_test.cc",
                "src/sentencepiece_processor_test.cc",
                "src/sentencepiece_trainer_test.cc",
                "src/test_main.cc",
                "src/testharness.cc",
                "src/trainer_factory_test.cc",
                "src/trainer_interface_test.cc",
                "src/unicode_script_test.cc",
                "src/unigram_model_test.cc",
                "src/unigram_model_trainer_test.cc",
                "src/util_test.cc",
                "src/word_model_test.cc",
                "src/word_model_trainer_test.cc",
                "src/pretokenizer_for_training_test.cc",
                // Executable main files
                "src/spm_encode_main.cc",
                "src/spm_decode_main.cc",
                "src/spm_normalize_main.cc",
                "src/spm_train_main.cc",
                "src/spm_export_vocab_main.cc",
                "src/compile_charsmap_main.cc",
                // Proto source files (not C++)
                "src/sentencepiece.proto",
                "src/sentencepiece_model.proto",
            ],
            sources: [
                // Core sentencepiece
                "src/bpe_model.cc",
                "src/char_model.cc",
                "src/filesystem.cc",
                "src/init.cc",
                "src/model_factory.cc",
                "src/model_interface.cc",
                "src/normalizer.cc",
                "src/sentencepiece_processor.cc",
                "src/unigram_model.cc",
                "src/util.cc",
                "src/word_model.cc",
                // Training
                "src/builder.cc",
                "src/unicode_script.cc",
                "src/trainer_factory.cc",
                "src/trainer_interface.cc",
                "src/unigram_model_trainer.cc",
                "src/word_model_trainer.cc",
                "src/char_model_trainer.cc",
                "src/bpe_model_trainer.cc",
                "src/sentencepiece_trainer.cc",
                "src/pretokenizer_for_training.cc",
                // Builtin protobuf
                "src/builtin_pb/sentencepiece.pb.cc",
                "src/builtin_pb/sentencepiece_model.pb.cc",
                // Internal protobuf-lite
                "third_party/protobuf-lite/arena.cc",
                "third_party/protobuf-lite/arenastring.cc",
                "third_party/protobuf-lite/bytestream.cc",
                "third_party/protobuf-lite/coded_stream.cc",
                "third_party/protobuf-lite/common.cc",
                "third_party/protobuf-lite/extension_set.cc",
                "third_party/protobuf-lite/generated_enum_util.cc",
                "third_party/protobuf-lite/generated_message_table_driven_lite.cc",
                "third_party/protobuf-lite/generated_message_util.cc",
                "third_party/protobuf-lite/implicit_weak_message.cc",
                "third_party/protobuf-lite/int128.cc",
                "third_party/protobuf-lite/io_win32.cc",
                "third_party/protobuf-lite/message_lite.cc",
                "third_party/protobuf-lite/parse_context.cc",
                "third_party/protobuf-lite/repeated_field.cc",
                "third_party/protobuf-lite/status.cc",
                "third_party/protobuf-lite/statusor.cc",
                "third_party/protobuf-lite/stringpiece.cc",
                "third_party/protobuf-lite/stringprintf.cc",
                "third_party/protobuf-lite/structurally_valid.cc",
                "third_party/protobuf-lite/strutil.cc",
                "third_party/protobuf-lite/time.cc",
                "third_party/protobuf-lite/wire_format_lite.cc",
                "third_party/protobuf-lite/zero_copy_stream.cc",
                "third_party/protobuf-lite/zero_copy_stream_impl.cc",
                "third_party/protobuf-lite/zero_copy_stream_impl_lite.cc",
                // Abseil 20260526.0 implementation sources required by
                // SentencePiece 0.2.2.
                "third_party/absl/base/casts.cc",
                "third_party/absl/base/internal/cycleclock.cc",
                "third_party/absl/base/internal/low_level_alloc.cc",
                "third_party/absl/base/internal/raw_logging.cc",
                "third_party/absl/base/internal/spinlock.cc",
                "third_party/absl/base/internal/spinlock_wait.cc",
                "third_party/absl/base/internal/strerror.cc",
                "third_party/absl/base/internal/sysinfo.cc",
                "third_party/absl/base/internal/thread_identity.cc",
                "third_party/absl/base/internal/tracing.cc",
                "third_party/absl/base/internal/unscaledcycleclock.cc",
                "third_party/absl/base/log_severity.cc",
                "third_party/absl/base/throw_delegate.cc",
                "third_party/absl/container/internal/hashtablez_sampler.cc",
                "third_party/absl/container/internal/hashtablez_sampler_force_weak_definition.cc",
                "third_party/absl/container/internal/raw_hash_set.cc",
                "third_party/absl/crc/crc32c.cc",
                "third_party/absl/crc/internal/cpu_detect.cc",
                "third_party/absl/crc/internal/crc.cc",
                "third_party/absl/crc/internal/crc_cord_state.cc",
                "third_party/absl/crc/internal/crc_memcpy_fallback.cc",
                "third_party/absl/crc/internal/crc_memcpy_x86_arm_combined.cc",
                "third_party/absl/crc/internal/crc_non_temporal_memcpy.cc",
                "third_party/absl/crc/internal/crc_x86_arm_combined.cc",
                "third_party/absl/debugging/internal/address_is_readable.cc",
                "third_party/absl/debugging/internal/decode_rust_punycode.cc",
                "third_party/absl/debugging/internal/demangle.cc",
                "third_party/absl/debugging/internal/demangle_rust.cc",
                "third_party/absl/debugging/internal/elf_mem_image.cc",
                "third_party/absl/debugging/internal/examine_stack.cc",
                "third_party/absl/debugging/internal/utf8_for_code_point.cc",
                "third_party/absl/debugging/internal/vdso_support.cc",
                "third_party/absl/debugging/leak_check.cc",
                "third_party/absl/debugging/stacktrace.cc",
                "third_party/absl/debugging/symbolize.cc",
                "third_party/absl/flags/commandlineflag.cc",
                "third_party/absl/flags/internal/commandlineflag.cc",
                "third_party/absl/flags/internal/flag.cc",
                "third_party/absl/flags/internal/private_handle_accessor.cc",
                "third_party/absl/flags/internal/program_name.cc",
                "third_party/absl/flags/internal/usage.cc",
                "third_party/absl/flags/marshalling.cc",
                "third_party/absl/flags/parse.cc",
                "third_party/absl/flags/reflection.cc",
                "third_party/absl/flags/usage.cc",
                "third_party/absl/flags/usage_config.cc",
                "third_party/absl/hash/internal/city.cc",
                "third_party/absl/hash/internal/hash.cc",
                "third_party/absl/log/globals.cc",
                "third_party/absl/log/initialize.cc",
                "third_party/absl/log/log_entry.cc",
                "third_party/absl/log/log_sink.cc",
                "third_party/absl/log/internal/check_op.cc",
                "third_party/absl/log/internal/conditions.cc",
                "third_party/absl/log/internal/fnmatch.cc",
                "third_party/absl/log/internal/globals.cc",
                "third_party/absl/log/internal/log_format.cc",
                "third_party/absl/log/internal/log_message.cc",
                "third_party/absl/log/internal/log_sink_set.cc",
                "third_party/absl/log/internal/nullguard.cc",
                "third_party/absl/log/internal/proto.cc",
                "third_party/absl/log/internal/structured_proto.cc",
                "third_party/absl/log/internal/vlog_config.cc",
                "third_party/absl/numeric/int128.cc",
                "third_party/absl/profiling/internal/exponential_biased.cc",
                "third_party/absl/random/discrete_distribution.cc",
                "third_party/absl/random/gaussian_distribution.cc",
                "third_party/absl/random/seed_gen_exception.cc",
                "third_party/absl/random/seed_sequences.cc",
                "third_party/absl/random/internal/entropy_pool.cc",
                "third_party/absl/random/internal/randen.cc",
                "third_party/absl/random/internal/randen_detect.cc",
                "third_party/absl/random/internal/randen_hwaes.cc",
                "third_party/absl/random/internal/randen_round_keys.cc",
                "third_party/absl/random/internal/randen_slow.cc",
                "third_party/absl/random/internal/seed_material.cc",
                "third_party/absl/status/internal/status_internal.cc",
                "third_party/absl/status/status.cc",
                "third_party/absl/status/status_builder.cc",
                "third_party/absl/status/status_payload_printer.cc",
                "third_party/absl/status/statusor.cc",
                "third_party/absl/strings/ascii.cc",
                "third_party/absl/strings/charconv.cc",
                "third_party/absl/strings/cord.cc",
                "third_party/absl/strings/cord_analysis.cc",
                "third_party/absl/strings/escaping.cc",
                "third_party/absl/strings/internal/charconv_bigint.cc",
                "third_party/absl/strings/internal/charconv_parse.cc",
                "third_party/absl/strings/internal/cord_internal.cc",
                "third_party/absl/strings/internal/cord_rep_btree.cc",
                "third_party/absl/strings/internal/cord_rep_btree_navigator.cc",
                "third_party/absl/strings/internal/cord_rep_btree_reader.cc",
                "third_party/absl/strings/internal/cord_rep_consume.cc",
                "third_party/absl/strings/internal/cord_rep_crc.cc",
                "third_party/absl/strings/internal/cordz_functions.cc",
                "third_party/absl/strings/internal/cordz_handle.cc",
                "third_party/absl/strings/internal/cordz_info.cc",
                "third_party/absl/strings/internal/damerau_levenshtein_distance.cc",
                "third_party/absl/strings/internal/escaping.cc",
                "third_party/absl/strings/internal/memutil.cc",
                "third_party/absl/strings/internal/ostringstream.cc",
                "third_party/absl/strings/internal/str_format/arg.cc",
                "third_party/absl/strings/internal/str_format/bind.cc",
                "third_party/absl/strings/internal/str_format/extension.cc",
                "third_party/absl/strings/internal/str_format/float_conversion.cc",
                "third_party/absl/strings/internal/str_format/output.cc",
                "third_party/absl/strings/internal/str_format/parser.cc",
                "third_party/absl/strings/internal/stringify_sink.cc",
                "third_party/absl/strings/internal/utf8.cc",
                "third_party/absl/strings/match.cc",
                "third_party/absl/strings/numbers.cc",
                "third_party/absl/strings/str_cat.cc",
                "third_party/absl/strings/str_replace.cc",
                "third_party/absl/strings/str_split.cc",
                "third_party/absl/strings/substitute.cc",
                "third_party/absl/synchronization/barrier.cc",
                "third_party/absl/synchronization/blocking_counter.cc",
                "third_party/absl/synchronization/internal/create_thread_identity.cc",
                "third_party/absl/synchronization/internal/futex_waiter.cc",
                "third_party/absl/synchronization/internal/graphcycles.cc",
                "third_party/absl/synchronization/internal/kernel_timeout.cc",
                "third_party/absl/synchronization/internal/per_thread_sem.cc",
                "third_party/absl/synchronization/internal/pthread_waiter.cc",
                "third_party/absl/synchronization/internal/sem_waiter.cc",
                "third_party/absl/synchronization/internal/stdcpp_waiter.cc",
                "third_party/absl/synchronization/internal/waiter_base.cc",
                "third_party/absl/synchronization/internal/win32_waiter.cc",
                "third_party/absl/synchronization/mutex.cc",
                "third_party/absl/synchronization/notification.cc",
                "third_party/absl/time/civil_time.cc",
                "third_party/absl/time/clock.cc",
                "third_party/absl/time/duration.cc",
                "third_party/absl/time/format.cc",
                "third_party/absl/time/time.cc",
                "third_party/absl/time/internal/cctz/src/civil_time_detail.cc",
                "third_party/absl/time/internal/cctz/src/time_zone_fixed.cc",
                "third_party/absl/time/internal/cctz/src/time_zone_format.cc",
                "third_party/absl/time/internal/cctz/src/time_zone_if.cc",
                "third_party/absl/time/internal/cctz/src/time_zone_impl.cc",
                "third_party/absl/time/internal/cctz/src/time_zone_info.cc",
                "third_party/absl/time/internal/cctz/src/time_zone_libc.cc",
                "third_party/absl/time/internal/cctz/src/time_zone_lookup.cc",
                "third_party/absl/time/internal/cctz/src/time_zone_posix.cc",
                "third_party/absl/time/internal/cctz/src/zone_info_source.cc",
                "third_party/absl/types/source_location.cc",
            ] + platformAbseilSources,
            publicHeadersPath: "include",
            cxxSettings: [
                .headerSearchPath("include"),
                .headerSearchPath("src"),
                .headerSearchPath("src/builtin_pb"),
                .headerSearchPath("third_party"),
                .headerSearchPath("third_party/protobuf-lite"),
                .headerSearchPath("third_party/absl"),
                .headerSearchPath("."),
                .define("HAVE_PTHREAD", to: "1"),
            ],
            linkerSettings: [
                .linkedLibrary("m", .when(platforms: [.linux])),
            ]
        ),
        // Executable targets
        .executableTarget(
            name: "spm_encode",
            dependencies: ["swift-package-support-sentencepiece"],
            path: "src",
            sources: ["spm_encode_main.cc"],
            cxxSettings: [
                .headerSearchPath("."),
                .headerSearchPath("builtin_pb"),
                .headerSearchPath(".."),
                .headerSearchPath("../third_party"),
                .headerSearchPath("../third_party/protobuf-lite"),
                .headerSearchPath("../third_party/absl"),
                .define("HAVE_PTHREAD", to: "1"),
            ]
        ),
        .executableTarget(
            name: "spm_decode",
            dependencies: ["swift-package-support-sentencepiece"],
            path: "src",
            sources: ["spm_decode_main.cc"],
            cxxSettings: [
                .headerSearchPath("."),
                .headerSearchPath("builtin_pb"),
                .headerSearchPath(".."),
                .headerSearchPath("../third_party"),
                .headerSearchPath("../third_party/protobuf-lite"),
                .headerSearchPath("../third_party/absl"),
                .define("HAVE_PTHREAD", to: "1"),
            ]
        ),
        .executableTarget(
            name: "spm_normalize",
            dependencies: ["swift-package-support-sentencepiece"],
            path: "src",
            sources: ["spm_normalize_main.cc"],
            cxxSettings: [
                .headerSearchPath("."),
                .headerSearchPath("builtin_pb"),
                .headerSearchPath(".."),
                .headerSearchPath("../third_party"),
                .headerSearchPath("../third_party/protobuf-lite"),
                .headerSearchPath("../third_party/absl"),
                .define("HAVE_PTHREAD", to: "1"),
            ]
        ),
        .executableTarget(
            name: "spm_train",
            dependencies: ["swift-package-support-sentencepiece"],
            path: "src",
            sources: ["spm_train_main.cc"],
            cxxSettings: [
                .headerSearchPath("."),
                .headerSearchPath("builtin_pb"),
                .headerSearchPath(".."),
                .headerSearchPath("../third_party"),
                .headerSearchPath("../third_party/protobuf-lite"),
                .headerSearchPath("../third_party/absl"),
                .define("HAVE_PTHREAD", to: "1"),
            ]
        ),
        .executableTarget(
            name: "spm_export_vocab",
            dependencies: ["swift-package-support-sentencepiece"],
            path: "src",
            sources: ["spm_export_vocab_main.cc"],
            cxxSettings: [
                .headerSearchPath("."),
                .headerSearchPath("builtin_pb"),
                .headerSearchPath(".."),
                .headerSearchPath("../third_party"),
                .headerSearchPath("../third_party/protobuf-lite"),
                .headerSearchPath("../third_party/absl"),
                .define("HAVE_PTHREAD", to: "1"),
            ]
        ),
        // Test target
        .executableTarget(
            name: "spm_test",
            dependencies: ["swift-package-support-sentencepiece"],
            path: "src",
            sources: [
                "test_main.cc",
                "testharness.cc",
                "bpe_model_test.cc",
                "bpe_model_trainer_test.cc",
                "builder_test.cc",
                "char_model_test.cc",
                "char_model_trainer_test.cc",
                "filesystem_test.cc",
                "invalid_model_test.cc",
                "model_factory_test.cc",
                "model_interface_test.cc",
                "normalizer_test.cc",
                "sentencepiece_processor_parallel_test.cc",
                "sentencepiece_processor_test.cc",
                "sentencepiece_trainer_test.cc",
                "trainer_factory_test.cc",
                "trainer_interface_test.cc",
                "unicode_script_test.cc",
                "unigram_model_test.cc",
                "unigram_model_trainer_test.cc",
                "util_test.cc",
                "word_model_test.cc",
                "word_model_trainer_test.cc",
                "pretokenizer_for_training_test.cc",
            ],
            cxxSettings: [
                .headerSearchPath("."),
                .headerSearchPath("builtin_pb"),
                .headerSearchPath(".."),
                .headerSearchPath("../third_party"),
                .headerSearchPath("../third_party/protobuf-lite"),
                .headerSearchPath("../third_party/absl"),
                .define("HAVE_PTHREAD", to: "1"),
                .unsafeFlags(["-Wno-sign-compare"]),
            ]
        ),
    ],
    cxxLanguageStandard: .cxx17
)
